package repository;

import config.DatabaseConfig;
import model.PurchaseOrder;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * PurchaseOrderRepository: CRUD for Purchase Orders
 * Purchase creates POs → Accounts tracks billing/payment
 */
public class PurchaseOrderRepository {

    /**
     * Create a new Purchase Order (generated by Purchase department)
     */
    public boolean createPO(PurchaseOrder po) {
        String sql = "INSERT INTO purchase_orders (pr_id, vendor_name, total_cost, status, notes) " +
                "VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, po.getPrId());
            pstmt.setString(2, po.getVendorName());
            pstmt.setBigDecimal(3, po.getTotalCost());
            pstmt.setString(4, po.getStatus());
            pstmt.setString(5, po.getNotes());

            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            System.err.println("Error creating purchase order: " + e.getMessage());
            return false;
        }
    }

    /**
     * Get all CREATED POs (not yet billed/paid)
     */
    public List<PurchaseOrder> getCreatedPOs() {
        String sql = "SELECT * FROM purchase_orders WHERE status = 'CREATED' ORDER BY created_date ASC";
        return executeQuery(sql);
    }

    /**
     * Get all BILLED POs (awaiting payment)
     */
    public List<PurchaseOrder> getBilledPOs() {
        String sql = "SELECT * FROM purchase_orders WHERE status = 'BILLED' ORDER BY created_date ASC";
        return executeQuery(sql);
    }

    /**
     * Get all PAID POs (completed)
     */
    public List<PurchaseOrder> getPaidPOs() {
        String sql = "SELECT * FROM purchase_orders WHERE status = 'PAID' ORDER BY created_date DESC";
        return executeQuery(sql);
    }

    /**
     * Get PO by ID
     */
    public PurchaseOrder getPOById(int poId) {
        String sql = "SELECT * FROM purchase_orders WHERE po_id = ?";

        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, poId);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                return parseRow(rs);
            }
        } catch (SQLException e) {
            System.err.println("Error fetching PO by ID: " + e.getMessage());
        }
        return null;
    }

    /**
     * Get POs linked to a Purchase Request
     */
    public List<PurchaseOrder> getPOsByPR(int prId) {
        String sql = "SELECT * FROM purchase_orders WHERE pr_id = ?";

        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, prId);
            return parseResults(pstmt.executeQuery());
        } catch (SQLException e) {
            System.err.println("Error fetching POs for PR: " + e.getMessage());
            return new ArrayList<>();
        }
    }

    /**
     * Update PO status (CREATED → BILLED → PAID)
     */
    public boolean updatePOStatus(int poId, String newStatus) {
        String sql = "UPDATE purchase_orders SET status = ? WHERE po_id = ?";

        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, newStatus);
            pstmt.setInt(2, poId);

            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            System.err.println("Error updating PO status: " + e.getMessage());
            return false;
        }
    }

    /**
     * Mark PO as PAID with payment date
     */
    public boolean markAsPaid(int poId, LocalDateTime paymentDate) {
        String sql = "UPDATE purchase_orders SET status = 'PAID', payment_date = ? WHERE po_id = ?";

        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setTimestamp(1, Timestamp.valueOf(paymentDate));
            pstmt.setInt(2, poId);

            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            System.err.println("Error marking PO as paid: " + e.getMessage());
            return false;
        }
    }

    /**
     * Get all POs (for admin/dashboard)
     */
    public List<PurchaseOrder> getAllPOs() {
        String sql = "SELECT * FROM purchase_orders ORDER BY created_date DESC";
        return executeQuery(sql);
    }

    /**
     * Get total spending by vendor
     */
    public List<Object[]> getSpendingByVendor() {
        String sql = "SELECT vendor_name, SUM(total_cost) as total_spent FROM purchase_orders " +
                "WHERE status = 'PAID' GROUP BY vendor_name ORDER BY total_spent DESC";

        List<Object[]> results = new ArrayList<>();
        try (Connection conn = DatabaseConfig.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                results.add(new Object[]{
                        rs.getString("vendor_name"),
                        rs.getBigDecimal("total_spent")
                });
            }
        } catch (SQLException e) {
            System.err.println("Error getting vendor spending: " + e.getMessage());
        }
        return results;
    }

    public java.util.List<model.PurchaseOrder> getAllPurchaseOrders() {
        java.util.List<model.PurchaseOrder> orders = new java.util.ArrayList<>();
        String query = "SELECT * FROM purchase_orders"; // Update table name if yours differs

        try (java.sql.Connection conn = config.DatabaseConfig.getConnection();
             java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(query)) {

            while (rs.next()) {
                model.PurchaseOrder order = new model.PurchaseOrder(
                        rs.getInt("pr_id"),
                        rs.getString("vendor_name"),
                        rs.getBigDecimal("total_cost"),
                        rs.getString("notes")
                );
                orders.add(order);
            }
        } catch (java.sql.SQLException e) {
            System.err.println("Error fetching purchase orders: " + e.getMessage());
        }
        return orders;
    }

    // ============ HELPER METHODS ============

    private List<PurchaseOrder> executeQuery(String sql) {
        try (Connection conn = DatabaseConfig.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            return parseResults(rs);
        } catch (SQLException e) {
            System.err.println("Error executing query: " + e.getMessage());
            return new ArrayList<>();
        }
    }

    private List<PurchaseOrder> parseResults(ResultSet rs) throws SQLException {
        List<PurchaseOrder> pos = new ArrayList<>();
        while (rs.next()) {
            pos.add(parseRow(rs));
        }
        return pos;
    }

    private PurchaseOrder parseRow(ResultSet rs) throws SQLException {
        PurchaseOrder po = new PurchaseOrder();
        po.setPoId(rs.getInt("po_id"));
        po.setPrId(rs.getInt("pr_id"));
        po.setVendorName(rs.getString("vendor_name"));
        po.setTotalCost(rs.getBigDecimal("total_cost"));
        po.setCreatedDate(rs.getTimestamp("created_date").toLocalDateTime());
        po.setStatus(rs.getString("status"));

        Timestamp paymentTS = rs.getTimestamp("payment_date");
        if (paymentTS != null) {
            po.setPaymentDate(paymentTS.toLocalDateTime());
        }

        po.setNotes(rs.getString("notes"));
        return po;
    }
}