package ui;

import model.User;
import model.ProductRequest;
import model.PurchaseRequest;
import model.Resource;
import repository.ProductRequestRepository;
import repository.PurchaseRequestRepository;
import repository.ResourceRepository;

import java.util.Scanner;

/**
 * Stores Menu: Stores Department reviews requests, checks stock, and creates PRs
 * Flow: Stores (checks inventory) → If stock < quantity, create PR → Purchase Department
 */
public class StoresMenu {
    private final Scanner scanner;
    private final ProductRequestRepository productRequestRepo;
    private final PurchaseRequestRepository purchaseRequestRepo;
    private final ResourceRepository resourceRepo;

    public StoresMenu(Scanner scanner) {
        this.scanner = scanner;
        this.productRequestRepo = new ProductRequestRepository();
        this.purchaseRequestRepo = new PurchaseRequestRepository();
        this.resourceRepo = new ResourceRepository();
    }

    public void display(User storesUser) {
        boolean running = true;

        while (running) {
            System.out.println("\n" + "=".repeat(60));
            System.out.println("📦 STORES MENU");
            System.out.println("=".repeat(60));
            System.out.println("1. Review Pending Requests");
            System.out.println("2. Process Request (Check Stock & Fulfill/Create PR)");
            System.out.println("3. View Inventory Status");
            System.out.println("4. Logout");
            System.out.print("Select Option: ");

            String choice = scanner.nextLine().trim();

            switch (choice) {
                case "1" -> reviewPendingRequests();
                case "2" -> processRequest();
                case "3" -> viewInventoryStatus();
                case "4" -> {
                    System.out.println("✅ Logged out successfully.");
                    running = false;
                }
                default -> System.out.println("❌ Invalid option.");
            }
        }
    }

    private void reviewPendingRequests() {
        System.out.println("\n--- PENDING PRODUCT REQUESTS ---");

        var requests = productRequestRepo.getPendingRequests();
        if (requests.isEmpty()) {
            System.out.println("✅ No pending requests.");
            return;
        }

        System.out.printf("%-8s %-10s %-12s %-10s %-20s\n", "Req ID", "HOD ID", "Resource", "Qty", "Date");
        System.out.println("-".repeat(70));

        for (var req : requests) {
            System.out.printf("%-8d %-10d %-12d %-10d %-20s\n",
                    req.getRequestId(),
                    req.getHodId(),
                    req.getResourceId(),
                    req.getQuantity(),
                    req.getRequestedDate());
        }
    }

    private void processRequest() {
        System.out.println("\n--- PROCESS REQUEST ---");

        var requests = productRequestRepo.getPendingRequests();
        if (requests.isEmpty()) {
            System.out.println("✅ No pending requests to process.");
            return;
        }

        System.out.print("Enter Request ID to process: ");
        int requestId = Integer.parseInt(scanner.nextLine().trim());

        ProductRequest request = productRequestRepo.getRequestById(requestId);
        if (request == null) {
            System.out.println("❌ Request not found.");
            return;
        }

        Resource resource = resourceRepo.getResourceById(request.getResourceId());
        if (resource == null) {
            System.out.println("❌ Resource not found.");
            return;
        }

        System.out.println("\n📋 REQUEST DETAILS:");
        System.out.println("Resource: " + resource.getName());
        System.out.println("Requested Qty: " + request.getQuantity());
        System.out.println("Current Stock: " + resource.getQuantity_in_stock());

        // 🔑 KEY LOGIC: Stock check
        if (resource.getQuantity_in_stock() >= request.getQuantity()) {
            // Enough stock: FULFILL FROM INVENTORY
            System.out.println("\n✅ STOCK AVAILABLE - Fulfilling from inventory...");

            if (resourceRepo.deductInventory(request.getResourceId(), request.getQuantity())) {
                productRequestRepo.updateStatus(requestId, "FULFILLED_FROM_STOCK");
                System.out.println("✅ Request fulfilled from stock!");
            } else {
                System.out.println("❌ Failed to deduct inventory.");
            }
        } else {
            // Not enough stock: CREATE PURCHASE REQUEST
            System.out.println("\n⚠️ INSUFFICIENT STOCK - Creating Purchase Request...");

            PurchaseRequest pr = new PurchaseRequest(
                    requestId,
                    request.getResourceId(),
                    request.getQuantity(),
                    "Auto-generated by Stores: Stock insufficient"
            );

            if (purchaseRequestRepo.createPR(pr)) {
                productRequestRepo.updateStatus(requestId, "FORWARDED_TO_STORES");
                System.out.println("✅ Purchase Request created and forwarded to Purchase Department!");
            } else {
                System.out.println("❌ Failed to create purchase request.");
            }
        }
    }

    private void viewInventoryStatus() {
        System.out.println("\n--- INVENTORY STATUS ---");

        var resources = resourceRepo.getAllResources();
        if (resources.isEmpty()) {
            System.out.println("No resources in system.");
            return;
        }

        System.out.printf("%-8s %-40s %-10s %-12s %-12s\n",
                "ID", "Resource Name", "Category", "In Stock", "Unit Price");
        System.out.println("-".repeat(100));

        for (var r : resources) {
            String stockStatus = r.getQuantity_in_stock() <= 5 ? "⚠️ LOW" : "";
            System.out.printf("%-8d %-40s %-10s %-12d %-12.2f %s\n",
                    r.getResourceId(),
                    r.getName(),
                    r.getCategory(),
                    r.getQuantity_in_stock(),
                    r.getUnit_price(),
                    stockStatus);
        }
    }
}