package model;

import java.time.LocalDateTime;

/**
 * PurchaseRequest (PR): Generated by Stores when stock is insufficient
 * Workflow: Stores (detects low stock) → Purchase Department
 */
public class PurchaseRequest {
    private int prId;
    private int requestId; // Links back to ProductRequest
    private int resourceId;
    private int quantity;
    private LocalDateTime createdDate;
    private String status; // PENDING_PO, PO_ISSUED
    private String notes;

    // Constructors
    public PurchaseRequest() {}

    public PurchaseRequest(int requestId, int resourceId, int quantity, String notes) {
        this.requestId = requestId;
        this.resourceId = resourceId;
        this.quantity = quantity;
        this.status = "PENDING_PO";
        this.notes = notes;
    }

    // Getters & Setters
    public int getPrId() { return prId; }
    public void setPrId(int prId) { this.prId = prId; }

    public int getRequestId() { return requestId; }
    public void setRequestId(int requestId) { this.requestId = requestId; }

    public int getResourceId() { return resourceId; }
    public void setResourceId(int resourceId) { this.resourceId = resourceId; }

    public int getQuantity() { return quantity; }
    public void setQuantity(int quantity) { this.quantity = quantity; }

    public LocalDateTime getCreatedDate() { return createdDate; }
    public void setCreatedDate(LocalDateTime createdDate) { this.createdDate = createdDate; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }

    @Override
    public String toString() {
        return String.format("[PR#%d] LinkedRequest#%d | Resource#%d | Qty: %d | Status: %s",
                prId, requestId, resourceId, quantity, status);
    }
}