-- ============================================================================
-- CAMPUSFLOW SUPPLY CHAIN SCHEMA EXTENSION
-- Extended from existing users + resources to full supply chain workflow
-- ============================================================================

-- 1. DROP & RECREATE USERS TABLE with extended roles
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
                       user_id SERIAL PRIMARY KEY,
                       username VARCHAR(50) UNIQUE NOT NULL,
                       password VARCHAR(100) NOT NULL,
                       role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'FACULTY', 'HOD', 'STUDENT', 'STORES', 'PURCHASE', 'ACCOUNTS', 'BOARD_MEMBERS')),
                       department VARCHAR(50) NOT NULL,
                       year_of_study INT -- Nullable for Faculty/Admins/Dept Heads, populated for students
);

-- 2. RESOURCES TABLE (Inventory Master)
DROP TABLE IF EXISTS resources CASCADE;

CREATE TABLE resources (
                           resource_id SERIAL PRIMARY KEY,
                           name VARCHAR(100) NOT NULL,
                           category VARCHAR(50),
                           quantity_in_stock INT NOT NULL DEFAULT 0 CHECK (quantity_in_stock >= 0),
                           unit_price DECIMAL(10, 2) NOT NULL,
                           department VARCHAR(50) NOT NULL,
                           requires_approval BOOLEAN DEFAULT FALSE
);

-- 3. PRODUCT_REQUESTS TABLE (HOD → Stores)
-- HODs submit requests for items from inventory
DROP TABLE IF EXISTS product_requests CASCADE;

CREATE TABLE product_requests (
                                  request_id SERIAL PRIMARY KEY,
                                  hod_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                                  resource_id INT NOT NULL REFERENCES resources(resource_id) ON DELETE CASCADE,
                                  quantity INT NOT NULL CHECK (quantity > 0),
                                  requested_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  status VARCHAR(30) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'FULFILLED_FROM_STOCK', 'FORWARDED_TO_STORES')),
                                  notes TEXT
);

-- 4. PURCHASE_REQUESTS TABLE (Stores → Purchase)
-- Generated by Stores when stock is insufficient
DROP TABLE IF EXISTS purchase_requests CASCADE;

CREATE TABLE purchase_requests (
                                   pr_id SERIAL PRIMARY KEY,
                                   request_id INT NOT NULL REFERENCES product_requests(request_id) ON DELETE CASCADE,
                                   resource_id INT NOT NULL REFERENCES resources(resource_id) ON DELETE CASCADE,
                                   quantity INT NOT NULL CHECK (quantity > 0),
                                   created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   status VARCHAR(30) NOT NULL DEFAULT 'PENDING_PO' CHECK (status IN ('PENDING_PO', 'PO_ISSUED')),
                                   notes TEXT
);

-- 5. PURCHASE_ORDERS TABLE (Purchase → Accounts)
-- Generated by Purchase department, tracked by Accounts
DROP TABLE IF EXISTS purchase_orders CASCADE;

CREATE TABLE purchase_orders (
                                 po_id SERIAL PRIMARY KEY,
                                 pr_id INT NOT NULL REFERENCES purchase_requests(pr_id) ON DELETE CASCADE,
                                 vendor_name VARCHAR(100) NOT NULL,
                                 total_cost DECIMAL(12, 2) NOT NULL CHECK (total_cost > 0),
                                 created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 status VARCHAR(30) NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'BILLED', 'PAID')),
                                 payment_date TIMESTAMP,
                                 notes TEXT
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- GIN index on resources for quick lookups
CREATE INDEX idx_resources_department ON resources(department);

-- Indexes on foreign keys for faster joins
CREATE INDEX idx_product_requests_hod ON product_requests(hod_id);
CREATE INDEX idx_product_requests_resource ON product_requests(resource_id);
CREATE INDEX idx_product_requests_status ON product_requests(status);

CREATE INDEX idx_purchase_requests_request ON purchase_requests(request_id);
CREATE INDEX idx_purchase_requests_resource ON purchase_requests(resource_id);
CREATE INDEX idx_purchase_requests_status ON purchase_requests(status);

CREATE INDEX idx_purchase_orders_pr ON purchase_orders(pr_id);
CREATE INDEX idx_purchase_orders_status ON purchase_orders(status);

-- ============================================================================
-- SEED DATA: 7 Role Users + Test Resources
-- ============================================================================

-- Insert 7 Users (One for each role)
INSERT INTO users (username, password, role, department, year_of_study) VALUES
-- Academics
('cs_hod', 'hodpass', 'HOD', 'Computer Science', NULL),
('st_alex', 'studpass', 'STUDENT', 'Computer Science', 3),
('prof_smith', 'profpass', 'FACULTY', 'Computer Science', NULL),

-- Supply Chain
('stores_mgr', 'storespass', 'STORES', 'Store Operations', NULL),
('purchase_lead', 'purchasepass', 'PURCHASE', 'Procurement', NULL),
('acc_officer', 'accpass', 'ACCOUNTS', 'Finance', NULL),

-- Admin & Board
('board_chair', 'boardpass', 'BOARD_MEMBERS', 'Board Office', NULL),
('sys_admin', 'adminpass', 'ADMIN', 'Administration', NULL)
    ON CONFLICT (username) DO NOTHING;

-- Insert Test Resources (Inventory)
INSERT INTO resources (name, category, quantity_in_stock, unit_price, department, requires_approval) VALUES
                                                                                                         ('Laptop - Dell XPS 15', 'Electronics', 15, 95000.00, 'Computer Science', TRUE),
                                                                                                         ('Projector - Epson EB-2250U', 'Electronics', 5, 45000.00, 'Computer Science', TRUE),
                                                                                                         ('Whiteboard Markers - Set of 12', 'Stationery', 120, 500.00, 'Computer Science', FALSE),
                                                                                                         ('USB-C Cables - Bulk 50', 'Accessories', 45, 300.00, 'Computer Science', FALSE),
                                                                                                         ('Desk Chairs - Ergonomic', 'Furniture', 20, 12000.00, 'Computer Science', TRUE),
                                                                                                         ('Printer Paper - 500 sheets', 'Stationery', 200, 400.00, 'Computer Science', FALSE)
    ON CONFLICT DO NOTHING;

-- ============================================================================
-- TEST WORKFLOW SETUP (Optional - demonstrates a sample flow)
-- ============================================================================

-- Example: HOD requests 3 Laptops
INSERT INTO product_requests (hod_id, resource_id, quantity, status, notes)
VALUES (
           (SELECT user_id FROM users WHERE username = 'cs_hod'),
           (SELECT resource_id FROM resources WHERE name = 'Laptop - Dell XPS 15'),
           3,
           'PENDING',
           'Urgent: Lab equipment for new course'
       )
    ON CONFLICT DO NOTHING;

-- ============================================================================
-- VERIFICATION QUERIES (Run these to verify setup)
-- ============================================================================
-- SELECT COUNT(*) FROM users; -- Should show 8 users
-- SELECT COUNT(*) FROM resources; -- Should show 6 resources
-- SELECT * FROM users ORDER BY role;
-- SELECT * FROM resources ORDER BY department;