/*
package config;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class DatabaseConfig {
    // 5432 is the standard PostgreSQL port. campus_flow is your database name.
    private static final String URL = "jdbc:postgresql://localhost:5432/campus_flow";

    // Change "postgres" to your database username if you customized it during setup
    private static final String USER = "postgres";

    // CHANGE THIS: Put the actual password you created when installing PostgreSQL
    private static final String PASSWORD = "your_postgres_password";

    public static Connection getConnection() throws SQLException {
        try {
            // This loads the driver we downloaded via the pom.xml Maven file
            Class.forName("org.postgresql.Driver");
            return DriverManager.getConnection(URL, USER, PASSWORD);
        } catch (ClassNotFoundException e) {
            throw new SQLException("PostgreSQL JDBC Driver missing from project libraries.", e);
        }
    }
}
*/
/*
// H2 In-Memory Database Configuration

package config;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;

public class DatabaseConfig {
    // Mode=PostgreSQL tells H2 to understand standard Postgres syntax and compatibility rules
    private static final String URL = "jdbc:h2:mem:campus_flow;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    static {
        // Automatically build the required database layout in memory when the app starts
        try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
             Statement stmt = conn.createStatement()) {

            // 1. Create Role Enum/Check replacement for H2
            stmt.execute("CREATE TABLE IF NOT EXISTS users (" +
                    "user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "username VARCHAR(50) UNIQUE NOT NULL, " +
                    "password VARCHAR(100) NOT NULL, " +
                    "role VARCHAR(20) NOT NULL, " +
                    "department VARCHAR(50))");

            // 2. Seed our test student account directly into memory
            stmt.execute("MERGE INTO users KEY(username) VALUES (1, 'alice_stud', 'password123', 'STUDENT', 'Computer Science')");

        } catch (SQLException e) {
            System.err.println("Failed to initialize in-memory database: " + e.getMessage());
        }
    }

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }
}
 */

package config;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class DatabaseConfig {
    // 5432 is the standard PostgreSQL port. campus_flow is your database name.
    private static final String URL = "jdbc:postgresql://localhost:5432/campus_flow";

    // Change "postgres" to your database username if you customized it during setup
    private static final String USER = "postgres";

    // ⚠️ CHANGE THIS: Put the actual password you created when installing PostgreSQL on your machine
    private static final String PASSWORD = "LawsonDB";

    public static Connection getConnection() throws SQLException {
        try {
            // This explicitly loads the PostgreSQL driver from your pom.xml
            Class.forName("org.postgresql.Driver");
            return DriverManager.getConnection(URL, USER, PASSWORD);
        } catch (ClassNotFoundException e) {
            throw new SQLException("PostgreSQL JDBC Driver missing from project libraries.", e);
        }
    }
}