package model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * PurchaseOrder (PO): Generated by Purchase Department
 * Workflow: Purchase (creates PO) → Accounts (billing/payment tracking)
 */
public class PurchaseOrder {
    private int poId;
    private int prId; // Links to PurchaseRequest
    private String vendorName;
    private BigDecimal totalCost;
    private LocalDateTime createdDate;
    private String status; // CREATED, BILLED, PAID
    private LocalDateTime paymentDate;
    private String notes;

    // Constructors
    public PurchaseOrder() {}

    public PurchaseOrder(int prId, String vendorName, BigDecimal totalCost, String notes) {
        this.prId = prId;
        this.vendorName = vendorName;
        this.totalCost = totalCost;
        this.status = "CREATED";
        this.notes = notes;
    }

    // Getters & Setters
    public int getPoId() { return poId; }
    public void setPoId(int poId) { this.poId = poId; }

    public int getPrId() { return prId; }
    public void setPrId(int prId) { this.prId = prId; }

    public String getVendorName() { return vendorName; }
    public void setVendorName(String vendorName) { this.vendorName = vendorName; }

    public BigDecimal getTotalCost() { return totalCost; }
    public void setTotalCost(BigDecimal totalCost) { this.totalCost = totalCost; }

    public LocalDateTime getCreatedDate() { return createdDate; }
    public void setCreatedDate(LocalDateTime createdDate) { this.createdDate = createdDate; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getPaymentDate() { return paymentDate; }
    public void setPaymentDate(LocalDateTime paymentDate) { this.paymentDate = paymentDate; }

    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }

    @Override
    public String toString() {
        return String.format("[PO#%d] Vendor: %s | Cost: ₹%.2f | Status: %s | Created: %s",
                poId, vendorName, totalCost, status, createdDate);
    }
}